telemetry:
  build: ./
  restart: always
  ports:
    - "9000"
    - "9221:9221"
  expose:
    - "9221"
  environment:
    VIRTUAL_PORT: "9000"
    VIRTUAL_HOST: "telemetry.lab.metamask.io"
    LETSENCRYPT_HOST: "telemetry.lab.metamask.io"
    LETSENCRYPT_EMAIL: "admin@metamask.io"
